server:
  port: 8080
spring:
  application:
    name: spring-ai-alibaba
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  config:
    import:
      - "optional:nacos:prompt-config.json"
  nacos:
    username: nacos
    password: nacos
  ai:
    chat:
      client:
        enabled: false
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwq:32b
    dashscope:
      api-key:
    nacos:
      prompt:
        template:
          enabled: true